server:
  port: 10010
spring:
  application:
    name: api-gateway
blog:
  jwt:
    pubKeyPath:  G:\temp\rsa\rsa.pub # 公钥地址
    cookieName: BLOG_TOKEN # cookie的名称
  filter:
    allowPaths:
      - /api/user/register
      - /api/auth
      - /api/user/send
eureka:
  client:
    service-url:
      defaultZone: http://eureka01:10086/eureka,http://eureka02:10087/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
zuul:
  routes:
    blog-user-service: /user/** # 用户
    blog-auth-service: /auth/** # 授权中心微服务
  prefix: /api
  add-host-header: true
  sensitive-headers:
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms