spring:
  application:
    name: blog-common
  #redis 相关配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: -1
#eureka 相关配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka01:10086/eureka,http://eureka02:10087/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
server:
  port: 11000
